---
title: "Lab 02 - Global plastic waste"
author: "Team Name: Blair Rafferty, Ben Heron, Hannah Teasdale and Alan Smithee"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message = FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
```


## Load & join data sets

```{r load-data, message = FALSE}
# Member 1 write code to load File 1 data here:

Plastic <- read.csv("data/mismanaged-plastic-waste-per-capita.csv")

# Member 2 write code to load File 2 data here:

Plastic_2 <- read.csv2("data/per-capita-ocean-plastic-waste.txt")

# Member 3 write code to load File 3 data here:

UN_country_population <- read_tsv("data/UN_country_population.tsv")

# Member 4 write code to load File 4 data here:

library(readxl)
UN_country_region <- read_excel("data/UN_country_region.xlsx")

```



```{r join-data, message = FALSE}
# Member 1 write code to create object 'plastic_data_all':



# Member 2 write code to join your data to 'plastic_data_all':



# Member 3 write code to join your data to 'plastic_data_all':



# Member 4 write code to join your data to 'plastic_data_all':



```


```{r print-data, message = FALSE}
# Member 1 adds code here to view the first 10 rows of 'plastic_data_all'



```



## Exercises

### Ex 1.

```{r Ex1, message = FALSE}
# Write your code here to answer exercise 1



```



### Ex 2.

```{r Ex2, message = FALSE}
# Write your code here to answer exercise 2



```


### Ex 3.

```{r Ex3, message = FALSE}
# Write your code here to answer exercise 3



```


### Ex 4.

```{r Ex4, message = FALSE}
# Write your code here to answer exercise 4



```
